aliases: []
creation_timestamp: 1773998028069
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1773998028069
metrics: null
model_id: m-5f86faf504f8406382d110772d948ee5
name: mlops-efficiency-predictor
params: null
run_id: 01224b84d30242818ec9ddc14b4ab4d2
run_link: null
source: models:/m-5f86faf504f8406382d110772d948ee5
status: READY
status_message: null
storage_location: file:///Users/ganeshlohar/Downloads/MATERIALS/ALL Materials - Jenkins
  Shared Library Project/CODE/PROJECT/mlruns_test/183879193069090132/models/m-5f86faf504f8406382d110772d948ee5/artifacts
user_id: null
version: 1
