artifact_location: file:///Users/ganeshlohar/Downloads/MATERIALS/ALL Materials - Jenkins
  Shared Library Project/CODE/PROJECT/mlruns_test/183879193069090132
creation_time: 1773997997181
experiment_id: '183879193069090132'
last_update_time: 1773997997181
lifecycle_stage: active
name: mlops-efficiency-prediction
