artifact_location: file:///Users/ganeshlohar/Downloads/MATERIALS/ALL Materials - Jenkins
  Shared Library Project/CODE/PROJECT/mlruns_test/0
creation_time: 1773997997169
experiment_id: '0'
last_update_time: 1773997997169
lifecycle_stage: active
name: Default
